name: collection_diff_worker
version: 0.5.5+4
homepage: https://github.com/SunnyApp/collection_diff_worker
description: An extension of the collection_diff library that allows the diffs to be performed asynchronously without blocking the main UI thread
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  collection: ^1.15.0
  collection_diff: ^2.0.3+3
  dartxx: ^0.4.5-nullsafety.6
  logging: ^1.0.0
  pedantic: ^1.11.0
  uuid: ^3.0.1
  worker_service: ^0.7.2+11
  isolates: ^3.0.3+7
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
